### ISSUE TITLE
[JOSS] How to model / predict for other years than the quickstarter years?

### ISSUE THREAD

**Issue by euronion** [IMMM-SFA/tell#39]
I wanted to run your model for some years which are not part of the quickstarter tutorial. Specifically:

```
# Run the MLP prediction step for a single BA (i.e., "region"):
pdf = tell.predict(region = 'ERCO',
                   year = 2045,
                   data_dir = os.path.join(tell_data_dir, r'sample_forcing_data', r'future_weather', r'rcp85hotter_ssp5'),
                   datetime_field_name = 'Time_UTC',
                   save_prediction = True,
                   prediction_output_directory = os.path.join(tell_data_dir, r'tell_quickstarter_data', r'outputs', r'mlp_output', r'rcp85hotter_ssp5'))

# View the prediction dataframe:
pdf
```

I do get an expected error:

```
FileNotFoundError: No data files were found for region 'ERCO' and year '2045' in directory '<...>/tell_data/sample_forcing_data/future_weather/rcp85hotter_ssp5'.
```

How do I prepare the necessary data? I have consulted the `tell_data_preprocessing.ipynb` notebook but I did not understand how that notebook produces the necessary input data for running your model outside the quickstart dataset boundaries.

**Comment by euronion** [comment]
xref https://github.com/openjournals/joss-reviews/issues/4472

**Comment by mcgrathc** [comment]
The process for producing meteorology input for TELL is somewhat complex and relies on multiple steps. In particular, future meteorology in the IM3 project (which supported the development of TELL) is created by dynamically downscaling data from a climate model. We have [companion code](https://github.com/IMMM-SFA/im3components/tree/main/im3components/wrf_to_tell) that takes the output from that downscaled climate model and converts it to input into TELL. As this relies on access to the raw data which is quite large we opted to instead provide a subset of four years of future meteorology data as part of the TELL quickstarter data package. This allows the reviewers and others interested in TELL to explore the model’s functionality without having to dive into the details of how the future weather files were created. Note also that TELL just needs a time-series of future weather in order to run. In our case the future weather comes from other IM3 models, but in principle it could be derived from other sources as long as they follow a similar format for their output files.

**Comment by mcgrathc** [comment]
Closing issue if no other comments apply. Will revisit if there are more questions.
